app:
  origin-permitida: "*"
  email-contato: renatoferrazdf@gmail.com
  seguranca:
    enable-https: false
  swagger:
    project-groupId: '@pom.groupId@'
    project-version: '@pom.version@'

spring:
  application:
    name: '@pom.artifactId@'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    generate-ddl: false
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

server:
  port: 8080


